services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - doapizza_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - doapizza_pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    command: >
      sh -c "
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  doapizza_postgres_data:
  doapizza_pgadmin_data:
