server {
    listen 80;
    server_name 89.208.96.100;

    client_max_body_size 20M;

    # Django static files — отдаются напрямую из тома
    location /static/ {
        alias /static/;
    }

    # Django media files — отдаются напрямую из тома
    location /media/ {
        alias /media/;
    }

    # Django admin panel
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django REST API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend SPA — всё остальное отдаётся как React-приложение
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
